---
title: "Daymet"
output: html_notebook
---

```{r}
library(raster)
library(rasterVis)
library(magrittr)
library(stringr)
library(zoo)
library(spacetime)
```

```{r}
bbox <- extent(-113.5, -106.5, 31, 37.5) #%>% projectExtent(crs = '+proj=longlat +datum=WGS84')
bbox.rast <- raster('Data/daymet_sample_bbox.tif')
bbox.rast
test1 <- brick('~/daac.ornl.gov/orders/ef03a1a25dcf9b227df9e209a04e942d/Daymet_V3_Monthly_Climatology/data/daymet_v3_prcp_monttl_1980_na.nc4')[[1]] %>% projectRaster(to = bbox.rast)

```


```{r}
getDaymet <- function(variable){
  var.dir <- paste0('~/Data/Daymet/', variable)
  files.in <- list.files(var.dir, full.names = T)
  
  sapply(files.in, function(x){
    brick(x) %>% projectRaster(bbox.rast)
  }) %>% brick #%>% stackApply(indices = 1:12, fun = mean)
}

prcp <- getDaymet('prcp')
```


```{r}
prcp
```

```{r}
levelplot(prcp[[100]], margin = F)
```

```{r}
times <- prcp %>% 
  names %>% 
  str_sub(2) %>% 
  str_replace_all('\\.','-') %>% 
  as.yearmon # use \\ to escape period
```

```{r}
stfdf <- prcp %>% setZ(times) %>% as('STFDF')
```


```{r}
## attempt to compute EOFs
#eof_time <- eof(stfdf, 'temporal')
eof_space <- eof(stfdf, 'spatial') %>% brick
eof(stfdf, 'spatial', returnEOFs = F) %>% screeplot()
```

```{r}
levelplot(eof_space[[1:6]] %>% resample(elev), par.settings = RdBuTheme())
```

