---
title: "Untitled"
author: "Nick Gauthier"
date: "January 22, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# SW Climate Analysis

Load packages
```{r}
library(tidyr)
library(raster)
library(rasterVis)
library(mgcv)
```


```{r}
bbox.rast <- raster('Data/daymet_sample_bbox.tif')

getDaymet <- function(variable){
  var.dir <- paste0('~/Data/Daymet/', variable)
  files.in <- list.files(var.dir, full.names = T)
  
  sapply(files.in, function(x){
    brick(x) %>% 
      projectRaster(bbox.rast)}) %>% 
    brick %>% stackApply(indices = 1:12, fun = mean)
}
```

```{r cache = T}
prcp <- getDaymet('prcp')
levelplot(prcp, par.settings = viridisTheme())

tmin <- getDaymet('tmin')
levelplot(tmin)

tmax <- getDaymet('tmax')
levelplot(tmax)
```

```{r}
val.vars <- readRDS('~/gdrive/Projects/GAMM Downscaling/val_vars') %>%
  lapply(projectRaster, to = prcp)

val.vars[[1]] %>% plot


levelplot(brick(c(val.vars[[8]][[4]], prcp[[8]])))
```

```{r}
elev <- raster('Data/swsn_NED_1.tif') %>% projectRaster(prcp)
levelplot(elev)
```


```{r}
plot(val.vars[[8]]$cp, prcp[[8]])
```

rain occurence
```{r}
levelplot(prcp > 1)
```

