---
title: "Analysis of landscape connectivity in the US Southwest"
author: "Nick Gauthier"
date: "March 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(gdistance)
library(rasterVis)
library(tidyverse)
```

Import the SWSN attribute file and reproject the UTM coordinates to Lat-Lon.
```{r swsn_in}
swsn.attr <- read_csv('Data/attributes_orig.csv') %>%
  select(-1) # drop ID column

swsn.pts <- swsn.attr %>% 
  select(x = EASTING, y = NORTHING) %>%
  SpatialPoints(proj4string=CRS("+proj=utm +zone=12 +datum=WGS84")) %>%
  spTransform(CRS("+proj=longlat +datum=WGS84")) %>% 
  coordinates

```

Generate a conductance layer using tobler's hiking function
```{r elevation}
elev <- raster('Data/swsn_NED_1.tif') %>% 
  crop(extent(c(-113, -106, 31, 37.5))) %>% 
  aggregate(fact = 10)
```

```{r transition}
altDiff <- function(x){x[2] - x[1]}
hd <- transition(elev, altDiff, 8, symm=FALSE)
adj <- adjacent(elev, cells=1:ncell(elev), pairs=TRUE, directions=8)
```

Create conductance matrix with geocorrection for lcps
```{r lcp_conductance}
slope.c <- geoCorrection(hd, type = 'c')
speed.c <- slope.c
speed.c[adj] <- 6 * exp(-3.5 * abs(slope.c[adj] + 0.05))
Conductance.c <- geoCorrection(speed.c, type = 'c')
rm(slope.c, speed.c)
```
Create conductance matrix with geocorrection for random walks
```{r randomwalk_conductance}
slope.r <- geoCorrection(hd, type = 'r')
speed.r <- slope.r
speed.r[adj] <- 6 * exp(-3.5 * abs(slope.r[adj] + 0.05))
Conductance.r <- geoCorrection(speed.r, type = 'r')
rm(slope.r, speed.r, hd, adj)
```

```{r lcp_calc}
cost_matrix <- costDistance(Conductance.c, swsn.pts)/3600
colnames(cost_matrix) <- swsn.attr$SWSN_Site

write_csv(as.data.frame(cost_matrix), 'Data/cost_matrix.csv')
```

```{r commute_calc}
commute_matrix <- costDistance(Conductance.r, swsn.pts)
colnames(commute_matrix) <- swsn.attr$SWSN_Site

write_csv(as.data.frame(commute_matrix), 'Data/commute_matrix.csv')
```


```{r}
spd1 <- rSPDistance(Conductance.r, swsn.pts, swsn.pts, 10)
```

```{r}
plot(c(cost_matrix), c(commute_matrix))
```



```{r}
for(i in 1:nrow(swsn.pts)){
  origin <- swsn.pts[i,]
  
  shortestPath(Conductance.c, origin, swsn.pts, output = 'SpatialLines')
}

test1 <- shortestPath(Conductance.c, swsn.pts[1,], swsn.pts[-1,], output = 'SpatialLines')
plot(test1)
test2 <- shortestPath(Conductance.c, swsn.pts[100,], swsn.pts[-100,], output = 'SpatialLines')
plot(test2)
```

