---
title: "R Notebook"
output: html_notebook
  keep_md: yes
---
```{r}
library(igraph)
library(GGally)
library(network)
library(sna)
library(tidyverse)
```



```{r}
swsn.pts <- read_csv('Data/attributes_orig.csv') %>% 
  select(easting = EASTING, northing = NORTHING) %>%
  SpatialPoints(proj4string=CRS("+proj=utm +zone=12 +datum=WGS84")) %>%
  spTransform(CRS("+proj=longlat +datum=WGS84")) %>% 
  coordinates %>%
  data.frame

swsn.attr <- read_csv('Data/attributes_orig.csv') %>%
  select(ID = SWSN_ID, site = SWSN_Site, macro = Macro, micro = Micro) %>%
  cbind(swsn.pts)
```

```{r}
readSWSN <- function(net){
  net.in <- read.csv(net, row.names = 1, check.names = F) 
  net.in[net.in < .75] <- 0
  net.in <- net.in %>% 
    as.matrix %>%
    graph_from_adjacency_matrix(mode = 'undirected', weighted = T, diag = F)
  
  ord <- match(V(net.in)$name, swsn.attr$site)

  V(net.in)$lon <- swsn.attr[ord, 5]
  V(net.in)$lat <- swsn.attr[ord, 6]
  V(net.in)$region <- swsn.attr[ord, 3] %>% as.character
  
  return(net.in)
}
```

```{r}
ad1200 <- readSWSN('Data/AD1200sim.csv')
```

```{r}
map <- ggmap(terrain.background)  +
  labs(x = "Longitude", y = "Latitude")

ggnetworkmap(map, ad1200, edge.size = 'weight', edge.alpha = .1, great.circles = T) +
  guides(size = F)

ggnet2(ad1200, mode = c('lon','lat'), size = 'degree', edge.size = 'weight', edge.alpha = .1) +
  guides(size = F)
  
```

