---
title: "Untitled"
author: "Nick Gauthier"
date: "October 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = FALSE}
library(raster)
library(tidyverse)
library(broom)
library(wql)
```
```{r}
bbox_wna <- extent(c(-124.5, -95, 18, 45))

```
```{r}
area_weight <- function(x){
  names_x <- names(x)
  x %>%
    init('y') %>% # get a map of latitudes
    `*`(pi/180) %>% # convert to radians
    cos %>%
    sqrt %>%
    `*`(x) %>%
    `names<-`(names_x)
}
```

This function calculates the effective observations in an autocorrelated time series of rasters.

```{R}
n_effective <- function(x){
  n <- nlayers(x)
  x %>%
    area_weight %>%
    as.data.frame(na.rm = TRUE) %>%
    t %>%
    as_tibble %>%
    gather(cell, value) %>%
    nest(value) %>%
    mutate(rho = map_dbl(data, ~cor(.$value, lag(.$value), use = 'comp')),
           effective_n = n * (1 - rho^2) / (1 + rho^2)) %>% #bretherton et al 1999

    summarise(mean(effective_n)) %>%
    pull
}
```

```{r}
get_obs <- function(x){
  brick(x) %>%
  crop(bbox_wna) %>%
  .[[-c(1:48)]] %>%
  .[[sort.int(c(seq(6,  1332, 12),seq(7,  1332, 12),seq(8,  1332, 12)))]] %>%
  stackApply(rep(1:111, each = 3), mean) 
}
do_pca <- function(x){
   x %>%
    area_weight %>%
  as.data.frame(na.rm = TRUE) %>%
  t %>%
  prcomp(scale. = FALSE) # use the covariance matrix
}
spei_obs_03 <- get_obs('data/spei03.nc')
spei_obs_06 <- get_obs('data/spei06.nc') 
spei_obs_12 <- get_obs('data/spei12.nc') 
spei_obs_24 <- get_obs('data/spei24.nc')
spei_obs_48 <- get_obs('data/spei48.nc')

1332/12
```

```{r}
do_pca <- function(x){
   x %>%
    area_weight %>%
  as.data.frame(na.rm = TRUE) %>%
  t %>%
  prcomp(scale. = FALSE) # use the covariance matrix
}
obs_pca_03 <- do_pca(spei_obs_03)
obs_pca_06 <- do_pca(spei_obs_06)
obs_pca_12 <- do_pca(spei_obs_12)
obs_pca_24 <- do_pca(spei_obs_24)
obs_pca_48 <- do_pca(spei_obs_48)

get_eigs <- function(x, y){
  x%>%
  tidy(matrix = 'pcs') %>%
  mutate(eigenvalues = std.dev ^ 2,
         error = sqrt(2 / n_effective(y)),
         low =  eigenvalues * (1 - error) * 100 / sum(eigenvalues),
         hi = eigenvalues * (1 + error) * 100 / sum(eigenvalues),
         cumvar_line = hi + 0.02 * max(hi))
}
obs_eigs_03 <- get_eigs(obs_pca_03, spei_obs_03) 
obs_eigs_06 <- get_eigs(obs_pca_06, spei_obs_06) 
obs_eigs_12 <- get_eigs(obs_pca_12, spei_obs_12)
obs_eigs_24 <- get_eigs(obs_pca_24, spei_obs_24)
obs_eigs_48 <- get_eigs(obs_pca_48, spei_obs_48)


eig_plot <- function(x){
  x %>% 
 # filter(eigenvalues > 1) %>%
  mutate(separated = if_else(is.na(lag(low)), TRUE, hi < lag(low)),
                   test = cumsum(separated),
         weights = if_else(PC < 50, 0, 1))%>%
    filter(PC <= 12) %>%
ggplot(aes(x = PC, y = percent * 100)) +
  geom_errorbar(aes(x = PC, ymin = low, ymax = hi), width = 0.4) +
  geom_point(size = 2, aes(color = as.factor(test))) + 
  geom_text(aes(x = PC, y = cumvar_line, label = round(cumulative * 100, 1)), size = 3, vjust = 0) +
  labs(list(x = "Principal Component", y = "Normalized Eigenvalue")) + 
  theme_bw() + guides(color = F) + scale_x_continuous(
    breaks = c(4, 8, 12)
  )
}

eig_plot(obs_eigs_03)
eig_plot(obs_eigs_06)
eig_plot(obs_eigs_12)
eig_plot(obs_eigs_24)
eig_plot(obs_eigs_48)
```

```{r}
n_modes <- 4 # choose 2, 4, 6, 9

obs_reof <- spei_obs_48 %>% 
  area_weight %>%
  as.data.frame(na.rm = TRUE) %>%
  t %>% # transpose space and time
  eof(n_modes, scale. = FALSE) # we don't rescale (ie we use the covariance matrix, because spei is already normalized and rescaled)

```

```{r}
get_EOFs <- function(pc_object, eigs, rast, n_modes){
  pc_object %>%
    tidy(matrix = 'variables') %>%
    filter(PC <= n_modes) %>%
    group_by(PC) %>%
    nest %>%
    left_join(eigs[1:2]) %>%
    mutate(data = future_map2(data, std.dev, ~mutate(.x, value = value * .y))) %>%
    unnest %>%
    bind_cols(as.data.frame(rast[[10]], xy = T, na.rm = T)[1:2] %>% slice(rep(1:n(), times = n_modes)))
}

eofs_obs_03 <- get_EOFs(obs_pca_03, obs_eigs_03, spei_obs_03, 4)
eofs_obs_06 <- get_EOFs(obs_pca_06, obs_eigs_06, spei_obs_06, 4)
eofs_obs_12 <- get_EOFs(obs_pca_12, obs_eigs_12, spei_obs_12, 4)
eofs_obs_24 <- get_EOFs(obs_pca_24, obs_eigs_24, spei_obs_24, 4)
eofs_obs_48 <- get_EOFs(obs_pca_48, obs_eigs_48, spei_obs_48, 4)
```

```{r plot_robs_eof, echo = FALSE, fig.width = 12, fig.height = 8, fig.cap = 'Observed drought REOFs'}
as.data.frame(spei_obs_48[[1]], xy = TRUE, na.rm = TRUE) %>% 
  cbind(obs_reof$REOF) %>%
  select(-3) %>%
  #mutate(EOF1 = EOF1 * -1, EOF2 = EOF2 * -1, EOF7 = EOF7 * -1) %>%
  gather(eof, value, 3:(n_modes + 2)) %>%
  mutate(value = value * -1) %>%
  ggplot(aes(x,y)) +
  geom_raster(aes(fill = value)) +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1,1)) +
  facet_wrap(~eof) +
  theme_void() +
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap() +
  #ggtitle(paste('Leading', n_modes, 'rotated empirical orthogonal functions')) +
  theme(legend.position = "bottom")

```


```{r}
ggplot(eofs_obs_03, aes(x, y, fill = value)) +
  facet_wrap(~PC) +
  geom_raster() +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1, 1)) +
  theme_void() + 
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap()
ggplot(eofs_obs_06, aes(x, y, fill = value)) +
  facet_wrap(~PC) +
  geom_raster() +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1, 1)) +
  theme_void() + 
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap()
ggplot(eofs_obs_12, aes(x, y, fill = value)) +
  facet_wrap(~PC) +
  geom_raster() +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1, 1)) +
  theme_void() + 
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap()
ggplot(eofs_obs_24, aes(x, y, fill = value)) +
  facet_wrap(~PC) +
  geom_raster() +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1, 1)) +
  theme_void() + 
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap()
ggplot(eofs_obs_48, aes(x, y, fill = value)) +
  facet_wrap(~PC) +
  geom_raster() +
  scale_fill_distiller(palette = 'BrBG', direction = 1, limits = c(-1, 1)) +
  theme_void() + 
  geom_polygon(data = states, aes(x = long, y = lat, group = region), color = 'black', fill = NA) +
  coord_quickmap()
```
```{r}
calc_amplitude <- function(x, n_modes){
  x %>%
    tidy(matrix = 'samples') %>%
    filter(PC <= n_modes) %>%
    rename(year = row, amplitude = value) %>%
    mutate(year = as.numeric(str_sub(year, 2)),
           PC = as.factor(PC)) %>%
    group_by(PC) %>%
    mutate(amplitude = scale(amplitude)) %>%
    ungroup
}

# this is the way to do it with the eofs, no reofs until i implement it
calc_amplitude(obs_pca_03, n_modes) %>%
  mutate(year = rep(1905:2015, 4)) %>%
  ggplot(aes(year, amplitude, group = PC, color = PC)) +
           geom_line() +
  facet_wrap(~PC)+geom_vline(xintercept = 1956) +geom_hline(yintercept = 0)
calc_amplitude(obs_pca_06, n_modes) %>%
  mutate(year = rep(1905:2015, 4)) %>%
  ggplot(aes(year, amplitude, group = PC, color = PC)) +
           geom_line() +
  facet_wrap(~PC)+geom_vline(xintercept = 1956) +geom_hline(yintercept = 0)
calc_amplitude(obs_pca_12, n_modes) %>%
  mutate(year = rep(1905:2015, 4)) %>%
  ggplot(aes(year, amplitude, group = PC, color = PC)) +
           geom_line() +
  facet_wrap(~PC)+geom_vline(xintercept = 1956) +geom_hline(yintercept = 0)
calc_amplitude(obs_pca_24, n_modes) %>%
  mutate(year = rep(1905:2015, 4)) %>%
  ggplot(aes(year, amplitude, group = PC, color = PC)) +
           geom_line() +
  facet_wrap(~PC)+geom_vline(xintercept = 1956) +geom_hline(yintercept = 0)
calc_amplitude(obs_pca_48, n_modes) %>%
  mutate(year = rep(1905:2015, 4)) %>%
  ggplot(aes(year, amplitude, group = PC, color = PC)) +
           geom_line() +
  facet_wrap(~PC) +geom_vline(xintercept = 1956) +geom_hline(yintercept = 0)
```

