---
title: "Southwest Climate Variability"
author: "Nicolas Gauthier"
date: Sys.Date()
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = F}
library(magrittr)
library(stringr)
library(raster)
library(SPEI)
library(spacetime)
library(zoo)
library(rasterVis)
```



```{r bbox}
bbox <- extent(-115.3997, -102.4102, 31.06377, 37.28437)
```


using index 4189 starts us in January 1199, so that we have a year lead for calculating spei
```{r import, cache = T}
prec <- brick('Data/b40.lm850-1850.1deg.001.cam2.h0.PRECT.085001-185012.nc') %>% 
  extract2(4189:7200) %>% 
  rotate %>%
  crop(bbox) %>%
  multiply_by(2.628e+9)

trefmnav <- brick('Data/b40.lm850-1850.1deg.001.cam2.h0.TREFMNAV.085001-185012.nc') %>%
  extract2(4189:7200) %>%
  rotate %>%
  crop(bbox) %>%
  subtract(273.15)
  
trefmxav <- brick('Data/b40.lm850-1850.1deg.001.cam2.h0.TREFMXAV.085001-185012.nc') %>%
  extract2(4189:7200) %>%
  rotate %>%
  crop(bbox) %>%
  subtract(273.15)
```


Interpolate climate data using splines.
```{r warnings = F}
library(fields)

tpsInterp <- function(rast.brick){
  target <- disaggregate(rast.brick[[1]], fact = 10, method = 'bilinear')
  
  lapply(1:nlayers(rast.brick), function(rast.index){
    rast.map <- rast.brick[[rast.index]]
    xy <- data.frame(xyFromCell(rast.map, 1:ncell(rast.map)))
    v <- getValues(rast.map)
    tps <- Tps(xy, v)
    interpolate(target, tps)
  }) %>% unlist %>% brick
}

prec.tps <- tpsInterp(prec)
prec.tps[prec.tps < 0] <- 0
trefmnav.tps <- tpsInterp(trefmnav)
trefmxav.tps <- tpsInterp(trefmxav)

writeRaster(prec.tps, 'Data/prec-sw.nc', overwrite = T)
writeRaster(trefmnav.tps, 'Data/trefmnav-sw.nc', overwrite = T)
writeRaster(trefmxav.tps, 'Data/trefmxav-sw.nc', overwrite = T)

levelplot(prec.tps[[1:4]])
levelplot(prec[[1:4]])
```


```{r times}
times <- prec %>% 
  names %>% 
  str_sub(2) %>% 
  str_replace_all('\\.','-') %>% 
  as.yearmon # use \\ to escape period
```

```{r lats}
lats <- init(prec.tps, 'y') %>% getValues
```

SPEI
```{r }
prcp.val <- getValues(prec.tps) %>% t   # need to transpose, getValues has rows for space and columns for time, hargreaves wants columns for space and rows for time
tmin.val <- getValues(trefmnav.tps) %>% t
tmax.val <- getValues(trefmxav.tps) %>% t
tmean.val <- getValues((trefmnav.tps + trefmxav.tps)/ 2) %>% t
```


```{r}
#pet <- hargreaves(tmin.val, tmax.val, lat = lats, Pre =  prcp.val, na.rm = T) %>% as.data.frame
pet <- thornthwaite(tmean.val, lats) %>% as.data.frame
pet.map <- setValues(prec.tps, t(pet))
levelplot(pet.map[[2]], margin = F)
```

```{r}
water.stress <- prcp.val - pet

ws.map <- setValues(prec.tps, t(water.stress))
levelplot(ws.map[[1:6]])
spei.fit <- spei(water.stress, scale = 12)
spei.rast <- setValues(prec.tps, t(spei.fit$fitted))[[13:3012]]

levelplot(spei.rast[[1:6]], par.settings = RdBuTheme())
```

```{r}
stfdf <- spei.rast %>% setZ(times[13:3012]) %>% as('STFDF')
```


```{r message = F}
## attempt to compute EOFs
eof_space <- eof(stfdf, 'spatial') %>% brick
eof_time <- eof(stfdf, 'temporal')
eof(stfdf, 'spatial', returnEOFs = F) %T>% screeplot()
```

```{r}
levelplot(eof_space[[1:6]], par.settings = RdBuTheme())
```

Now do it for each of the five periods.

```{r message = F}
eof.1200 <- spei.rast %>% setZ(times[13:3012]) %>% extract2(1:600) %>% as('STFDF') %>% eof('spatial') %>% brick %>% extract2(1:6)
levelplot(eof.1200, par.settings = RdBuTheme())
```

```{r warning=F}
eof.1250 <- spei.rast %>% setZ(times[13:3012]) %>% extract2(601:1200) %>% as('STFDF') %>% eof('spatial') %>% brick %>% extract2(1:6)
levelplot(eof.1250, par.setings = RdBuTheme())
```

```{r warning=F}
eof.1300 <- spei.rast %>% setZ(times[13:3012]) %>% extract2(1201:1800) %>% as('STFDF') %>% eof('spatial') %>% brick %>% extract2(1:6)
levelplot(eof.1300, par.settings = RdBuTheme())
```

```{r warning=F}
eof.1350 <- spei.rast %>% setZ(times[13:3012]) %>% extract2(1801:2400) %>% as('STFDF') %>% eof('spatial') %>% brick %>% extract2(1:6)
levelplot(eof.1350, par.settings = RdBuTheme())
```

```{r warning=F}
eof.1400 <- spei.rast %>% setZ(times[13:3012]) %>% extract2(2401:3000) %>% as('STFDF') %>% eof('spatial') %>% brick %>% extract2(1:6)
levelplot(eof.1400, par.settings = RdBuTheme())
```
      
      
      
```{r}
writeRaster(eof_space, 'eof_all.nc')
writeRaster(eof.1200, 'eof1200.nc')
writeRaster(eof.1250, 'eof1250.nc')
writeRaster(eof.1300, 'eof1300.nc')
writeRaster(eof.1350, 'eof1350.nc')
writeRaster(eof.1400, 'eof1400.nc')

```

```{r}

```

