---
title: "R Notebook"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    keep_md: yes
---

```{r}
tobler <- function(x){
  6 * exp(-3.5 * abs(x + .05))
}
```

```{r}
library(tidyverse)
```

```{r fig.width = 8, fig.height = 5}
slope <- seq(-1, 1, .01)
qplot(slope, tobler(slope), geom = 'line' ) +
  geom_vline(xintercept = 0, linetype = 2) +
  labs(x = 'Slope (rise over run)', y = 'Walking speed (m/s)', title = "Tobler's hiking function") +
  theme_classic(base_size = 20)
  
```

```{r}
test <- costDistance(Conductance, ad1200.pts) / 3600
test[test > 8] <- 0

```

```{r}
library(ggraph)
```
```{r}
ggraph(graph_from_adjacency_matrix(test, mode = 'plus', weighted = T)) +
    geom_edge_fan(alpha = .1) +
  geom_node_point(color = 'red') +
  theme_void()
```

```{r}
library(rasterVis)
Conductance2 <- geoCorrection(speed, type = 'r')
rSPraster <- passage(Conductance2, cbind(dat$from_lon, dat$from_lat), cbind(dat$to_lon, dat$to_lat), .001, totalNet = 'total')
rSPraster <- passage(Conductance, ad1200.pts, ad1200.pts, .05, totalNet = 'total')

rSPraster[rSPraster == 0] <- NA
levelplot(rSPraster, margin = F)
```

```{r}
sPath <- shortestPath(Conductance, cbind(dat$from_lon, dat$from_lat), cbind(dat$to_lon, dat$to_lat), output = 'SpatialLines')
rasterize(sPath, elev.agg, fun = 'count') %>% levelplot(margin = F)
```

