---
title: "Daymet"
output: html_notebook
---

```{r}
library(raster)
library(rasterVis)
library(magrittr)
library(SPEI)
library(stringr)
library(zoo)
library(spacetime)
library(bigmemory)
```

```{r}
bbox.rast <- raster('Data/daymet_sample_bbox.tif')
```


```{r}
getDaymet <- function(variable){
  var.dir <- paste0('~/Data/Daymet/', variable)
  files.in <- list.files(var.dir, full.names = T)
  
  sapply(files.in, function(x){
    brick(x) %>% projectRaster(bbox.rast)
  }) %>% brick #%>% stackApply(indices = 1:12, fun = mean)
}
```

```{r}
prcp <- getDaymet('prcp')
tmin <- getDaymet('tmin')
tmax <- getDaymet('tmax')
```
```{r}
times <- prcp %>% 
  names %>% 
  str_sub(2) %>% 
  str_replace_all('\\.','-') %>% 
  as.yearmon # use \\ to escape period
```

```{r}
#save files
writeRaster(prcp, 'Data/swsn_daymet_prcp.nc')
writeRaster(tmin, 'Data/swsn_daymet_tmin.nc')
writeRaster(tmax, 'Data/swsn_daymet_tmax.nc')
#load
prcp <- brick('Data/swsn_daymet_prcp.nc') %>% aggregate(fact = 10)  %>% crop(extent(291000, 931000, 3420000, 4160000))
tmin <- brick('Data/swsn_daymet_tmin.nc') %>% aggregate(fact = 10) %>% crop(extent(291000, 931000, 3420000, 4160000))
tmax <- brick('Data/swsn_daymet_tmax.nc') %>% aggregate(fact = 10) %>% crop(extent(291000, 931000, 3420000, 4160000))

```

SPEI
```{r}
prcp.val <- getValues(prcp) %>% t   # need to transpose, getValues has rows for space and columns for time, hargreaves wants columns for space and rows for time
tmin.val <- getValues(tmin) %>% t
tmax.val <- getValues(tmax) %>% t

#tmax.val <- as.big.matrix(tmax.val)
#tmin.val <- as.big.matrix(tmin.val)
#prcp.val <- as.big.matrix(prcp.val)

```



```{r}
dimnames(prcp.val) <- NULL
dimnames(tmin.val) <- NULL
dimnames(tmax.val) <- NULL

rm(prcp)
rm(tmin)
rm(tmax)
```

```{r}
lats <- rep(35, dim(tmax.val)[2])

pet <- hargreaves(tmin.val, tmax.val, lat = lats) %>% as.data.frame#as.matrix#, Pre = prcp.val) %>% as.matrix# using one latitude for now
pet <- thornthwaite((tmax.val + tmin.val) / 2, lat = lats)
pet.map <- setValues(prcp, t(pet))
levelplot(pet.map[[1]], margin = F)


water.stress <- prcp.val - pet

ws.map <- setValues(prcp, t(water.stress))
levelplot(ws.map[[268]], margin = F)
spei.test <- spei(water.stress, scale = 12)
```

```{r}
spei.rast <- setValues(prcp, t(spei.test$fitted))

levelplot(spei.rast[[268]], margin = F, par.settings = RdBuTheme())
```



```{r}
levelplot(!is.finite(spei.rast[[268]]), margin = F)

stfdf <- spei.rast[[which(cellStats(!is.finite(spei.rast), 'max') == 0)]] %>% setZ(times[which(cellStats(!is.finite(spei.rast), 'max') == 0)]) %>% as('STFDF')
spei.rast[[13:432]]


```

```{r}
## attempt to compute EOFs
#eof_time <- eof(stfdf, 'temporal')
eof_space <- eof(stfdf, 'spatial') %>% brick
eof(stfdf, 'spatial', returnEOFs = F) %>% screeplot()
```


```{r}
levelplot(eof_space[[1:6]], par.settings = RdBuTheme())
```


