---
title: "Spatial Downscaling of the Last Millennium Reanalysis over the American Southwest"
author: "Nick Gauthier"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# SW Climate Analysis

Load necessary packages.
```{r}
library(raster)
library(tidyverse)
library(gganimate)
library(fields)
library(mgcv)
```
```{r}
bbox <- extent(c(-115, -103, 31, 41))
```

Import Chelsa monthly data, aggregate to annual, and crop to region of interest
```{r}
prec <- list.files('~/Data/Chelsa/Monthly/prec', full.names = T) %>%
  map(~list.files(., full.names = T)) %>%
  map(~.[c(3, 5:12, 1:2, 4)]) %>%
  map(stack) %>%
  map(~crop(.x, bbox)) %>%
  brick %>%
  stackApply(rep(1:22, each = 12), sum)

names(prec) <- 1979:2000

writeRaster(prec, 'prec.tif', overwrite = T)
```

```{r}
library(gganimate)
library(viridis)
plt <- prec %>%
  as.data.frame(xy = T, na.rm = T) %>%
  gather(year, precipitation, 3:24) %>%
  mutate(year = str_sub(year, start = 2) %>% as.numeric) %>%
  ggplot(aes(x,y, frame = year)) +
  geom_raster(aes(fill = precipitation)) +
  theme_void() +
  coord_quickmap()+
  scale_fill_viridis()
  
gganimate(plt, 'animation.mp4')
```
```{r}
tpsInterp <- function(rast.brick){
  target <- resample(rast.brick[[1]], prec[[1]])
  lapply(1:nlayers(rast.brick), function(rast.index){
    rast.map <- rast.brick[[rast.index]]
    xy <- data.frame(xyFromCell(rast.map, 1:ncell(rast.map)))
    v <- getValues(rast.map)
    tps <- Tps(xy, v)
    interpolate(target, tps)
  }) %>% unlist %>% brick
}
```

Now compare to lmr
```{r}
prec_lmr <- brick('~/Desktop/data/hackathon_PAGES2kv1/pr_sfc_Amon_MCiters_ensemble_mean.nc') %>%
  .[[1980:2001]] %>%
  rotate %>%
  crop(bbox, snap = 'out') %>%
  tpsInterp
```

```{r}
plot(prec - mean(prec))
plot(prec - mean(prec), prec_lmr)
```

Now import large scale reanalysis data.
```{r}
processECMWF <- function(file, var){
  brick(paste0('~/gdrive/Data/', file), varname = var) %>%
      rotate %>% crop(prcp.obs)
}

tcw <- processECMWF('ecmwf_surface.nc', 'tcw')
msl <- processECMWF('ecmwf_surface.nc', 'msl')
t2m <- processECMWF('ecmwf_surface.nc', 't2m')
lsp <- processECMWF('ECMWF Precip.nc', 'lsp')
cp <- processECMWF('ECMWF Precip.nc', 'cp')
```
```


```{r}
bbox.rast <- raster('Data/daymet_sample_bbox.tif')

getDaymet <- function(variable){
  var.dir <- paste0('~/Data/Daymet/', variable)
  files.in <- list.files(var.dir, full.names = T)
  
  sapply(files.in, function(x){
    brick(x) %>% 
      projectRaster(bbox.rast)}) %>% 
    brick %>% stackApply(indices = 1:12, fun = mean)
}
```
